### <span style="color:orange">Importing the Libraries</span>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

### <span style="color:orange">Importing the Dataset</span>

In [2]:
dataset = pd.read_csv('Dataset\\Social_Network_Ads.csv')

In [3]:
dataset

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]

In [4]:
print(dataset)

     Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]


In [5]:
input_features = dataset.iloc[ : , :-1].values
dv = dataset.iloc[ : , -1].values

In [6]:
print(input_features)

[[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [7]:
print(dv)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


### <span style="color:orange">Splitting the Data</span>

In [8]:
from sklearn.model_selection import train_test_split

(input_features_train, input_features_test,
dv_train, dv_test) = train_test_split(input_features, dv, test_size=0.2, random_state=0)

In [9]:
print(input_features_train)

[[    58 144000]
 [    59  83000]
 [    24  55000]
 [    26  35000]
 [    58  38000]
 [    42  80000]
 [    40  75000]
 [    59 130000]
 [    46  41000]
 [    41  60000]
 [    42  64000]
 [    37 146000]
 [    23  48000]
 [    25  33000]
 [    24  84000]
 [    27  96000]
 [    23  63000]
 [    48  33000]
 [    48  90000]
 [    42 104000]
 [    44  39000]
 [    32 120000]
 [    38  50000]
 [    32 135000]
 [    52  21000]
 [    53 104000]
 [    39  42000]
 [    38  61000]
 [    36  50000]
 [    36  63000]
 [    35  25000]
 [    35  50000]
 [    42  73000]
 [    47  49000]
 [    59  29000]
 [    49  65000]
 [    45 131000]
 [    31  89000]
 [    46  82000]
 [    47  51000]
 [    26  15000]
 [    60 102000]
 [    38 112000]
 [    40 107000]
 [    42  53000]
 [    35  59000]
 [    48  41000]
 [    48 134000]
 [    38 113000]
 [    29 148000]
 [    26  15000]
 [    60  42000]
 [    24  19000]
 [    42 149000]
 [    46  96000]
 [    28  59000]
 [    39  96000]
 [    28  89000]
 [    41  7200

### <span style="color:orange">Feature Scaling</span>

##### <span style="color:orange">Standardization</span>

In [10]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()

In [11]:
## X-train
input_features_train = standard_scaler.fit_transform(input_features_train)

## X-test transform only
input_features_test = standard_scaler.transform(input_features_test)

In [12]:
print(input_features_train)

[[ 1.92295008e+00  2.14601566e+00]
 [ 2.02016082e+00  3.78719297e-01]
 [-1.38221530e+00 -4.32498705e-01]
 [-1.18779381e+00 -1.01194013e+00]
 [ 1.92295008e+00 -9.25023920e-01]
 [ 3.67578135e-01  2.91803083e-01]
 [ 1.73156642e-01  1.46942725e-01]
 [ 2.02016082e+00  1.74040666e+00]
 [ 7.56421121e-01 -8.38107706e-01]
 [ 2.70367388e-01 -2.87638347e-01]
 [ 3.67578135e-01 -1.71750061e-01]
 [-1.18475597e-01  2.20395980e+00]
 [-1.47942605e+00 -6.35303205e-01]
 [-1.28500455e+00 -1.06988428e+00]
 [-1.38221530e+00  4.07691369e-01]
 [-1.09058306e+00  7.55356227e-01]
 [-1.47942605e+00 -2.00722133e-01]
 [ 9.50842613e-01 -1.06988428e+00]
 [ 9.50842613e-01  5.81523798e-01]
 [ 3.67578135e-01  9.87132798e-01]
 [ 5.61999628e-01 -8.96051849e-01]
 [-6.04529329e-01  1.45068594e+00]
 [-2.12648508e-02 -5.77359062e-01]
 [-6.04529329e-01  1.88526701e+00]
 [ 1.33968560e+00 -1.41754914e+00]
 [ 1.43689635e+00  9.87132798e-01]
 [ 7.59458956e-02 -8.09135634e-01]
 [-2.12648508e-02 -2.58666276e-01]
 [-2.15686344e-01 -5

### <span style="color:orange">Training the Random Forest Model on the Training set</span>

In [13]:
from sklearn.ensemble import RandomForestClassifier
#
# Building the Model
random_F_classifier = RandomForestClassifier(n_estimators=10, random_state=0)
# Training the Model
random_F_classifier.fit(X=input_features_train, y=dv_train)

### <span style="color:orange">* The exhaustive grid search to optimize the hyperparameters</span>

In [14]:
## Preparing the parameter grid:

n_estimators = [int(x) for x in np.linspace(start = 10, stop = 200, num = 10)]
criterion = ['gini', 'entropy']
max_features = ['auto', 'sqrt', 'log2']
max_depth = [int(x) for x in np.linspace(10, 100, num = 10)]
min_samples_split = [2, 4, 8, 16]
min_samples_leaf = [2, 4, 8, 16]
bootstrap = [True, False]

param_grid = {'n_estimators': n_estimators,
                'criterion': criterion,
                'max_features': max_features,
                'max_depth': max_depth,
                'min_samples_split': min_samples_split,
                'min_samples_leaf': min_samples_leaf,
                'bootstrap': bootstrap}

In [15]:
## Finding the best parameters:

# from sklearn.ensemble import RandomForestClassifier
# from sklearn.model_selection import GridSearchCV
#
# random_F_classifier = RandomForestClassifier()
#
# # `n_jobs` means parallel jobs to run -> -1 means using all processors, I didn't use it because it uses 100% CPU
# grid_search = GridSearchCV(random_F_classifier, param_grid, cv = 3, verbose = 1)
#
# grid_fit = grid_search.fit(input_features_train, dv_train)
# grid_fit.best_params_

****I didn't continue it because it takes a long time, so I took the parameters of the poster**

In [16]:
## Use best params from the grid search
from sklearn.ensemble import RandomForestClassifier

# Building the model with the best parameters
random_F_classifier_grid_S = RandomForestClassifier(n_estimators=10,
                                        criterion='gini',
                                        bootstrap=True,
                                        max_depth=10,
                                        max_features='sqrt',
                                        min_samples_leaf=8,
                                        min_samples_split=2,
                                        random_state = 0)
# Training the model
random_F_classifier_grid_S.fit(input_features_train, dv_train)

RandomForestClassifier(max_depth=10, min_samples_leaf=8, n_estimators=10,
                       random_state=0)

### <span style="color:orange">Predicting a New Result</span>

In [17]:
## Predicting a new customer who is 30 years old with an estimated salary of $87,000
new_prediction = random_F_classifier_grid_S.predict(standard_scaler.transform([[30, 87000]] ) )

buy_prediction = ""
if new_prediction == 1:
    buy_prediction = 'buy'
elif new_prediction == 0:
    buy_prediction = 'not buy'

print("This customer is predicted to: ", buy_prediction)

This customer is predicted to:  not buy


### <span style="color:orange">Predicting the Test Set Results</span>

In [18]:
dv_predicted = random_F_classifier_grid_S.predict(input_features_test)

In [19]:
np.set_printoptions(precision=2)

print(np.concatenate((dv_predicted.reshape(len(dv_predicted), 1),
                      dv_test.reshape(len(dv_test), 1) ), axis=1) )
# // [dv_predicted dv_test]

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


### <span style="color:orange">**Making the Confusion Matrix and getting the Evaluation scores</span>

In [20]:
from sklearn.metrics import confusion_matrix

confusion_matrix_score = confusion_matrix(y_true=dv_test, y_pred=dv_predicted)
print(confusion_matrix_score)

[[55  3]
 [ 1 21]]


In [21]:
from sklearn.metrics import accuracy_score

accuracy_score = accuracy_score(y_true=dv_test, y_pred=dv_predicted)
print(accuracy_score)

0.95


In [22]:
from sklearn.metrics import precision_score

precision_score = precision_score(y_true=dv_test, y_pred=dv_predicted)
print(precision_score)

0.875


In [23]:
from sklearn.metrics import recall_score

recall_score = recall_score(y_true=dv_test, y_pred=dv_predicted)
print(recall_score)

0.9545454545454546


In [24]:
from sklearn.metrics import f1_score

f1_score = f1_score(y_true=dv_test, y_pred=dv_predicted)
print(f1_score)

0.9130434782608695


### <span style="color:orange">Visualizing the Test Set Results</span>

In [25]:
# from matplotlib.colors import ListedColormap
#
# input_features_set, dv_set = standard_scaler.inverse_transform(input_features_test), dv_test
# X1, X2 = np.meshgrid(np.arange(start=input_features_set[:, 0].min() - 10,
#                                stop=input_features_set[:, 0].max() + 10,
#                                step=0.25),
#                      np.arange(start=input_features_set[:, 1].min() - 1000,
#                                stop=input_features_set[:, 1].max() + 1000,
#                                step=0.25) )
#
# plt.contourf(X1, X2,
#              sv_classifier.predict(standard_scaler.transform(np.array(
#                  [X1.ravel(), X2.ravel()] ).T) ).reshape(X1.shape),
#              alpha=0.75, cmap=ListedColormap(('red', 'green') ) )
# plt.xlim(X1.min(), X1.max() )
# plt.ylim(X2.min(), X2.max() )
#
# for row, col in enumerate(np.unique(dv_set)):
#     plt.scatter(input_features_set[dv_set == col, 0],
#                 input_features_set[dv_set == col, 1],
#                 color = ListedColormap(('red', 'green') )(row),
#                 label = f'class[{col}]')
#
# plt.title('SVM (Test set)')
# plt.xlabel('Age')
# plt.ylabel('Estimated Salary')
# plt.legend()
# plt.show()

___

**Notes:**

**0.925 accuracy score for normal random forest**

**0.95 accuracy score for random forest with the best parameters**

**Better on every score except the precision score**